### PR TITLE
issue #142

### PR DESCRIPTION
**Pull request by tilo**
https://github.com/tilo/smarter_csv/issues/142

@KevinColemanInc

### CODE REVIEW

**Comment by tilo** [comment]
while this works, it would be better if users would do this instead:

```
data = SmarterCSV.process(your_filename, file_encoding: 'bom|utf-8')
```

**Comment by KevinColemanInc** [comment]
https://github.com/tilo/smarter_csv/issues/142#issuecomment-447625541

Updated my comment

**Comment by tilo** [comment]
@KevinColemanInc can you PM me on Twitter?

**Comment by tilo** [comment]
@KevinColemanInc the BOM issue was fixed in 1.8.0

**Pull request closed without merging**
