### PR TITLE
Refactor `guess_column_separator` logic

### PR DESCRIPTION
**Pull request by pioneerskies**
I found the original method's logic too prone to
fail even with simple scenarios. E.g., given this
CSV

```
id,description,created_at,updated_at
1,Acquaforte,2022-10-04 16:00:47 UTC,2022-10-04 16:00:47 UTC
2,Calcografia,2022-10-04 16:00:47 UTC,2022-10-04 16:00:47 UTC
3,Cromolitografia,2022-10-04 16:00:47 UTC,2022-10-04 16:00:47 UTC
4,Cromotipografia,2022-10-04 16:00:47 UTC,2022-10-04 16:00:47 UTC
5,Eliotipia,2022-10-04 16:00:47 UTC,2022-10-04 16:00:47 UTC
```

the guessed separator would be a colon (`:`) because we have only 4 columns separated by 3 commans (`,`), while in values there are 2 date-time-ish strings with 4 total colons (`:`) as hours/minutes/seconds separators.

My assumption here is that if we have headers in file, then the headers alone are the most affordable source of truth regarding the separator, thus we scan for possible separator only in the first line.

If we haven't headers, then we fallback to the original guessing algorithm.

This refactor turns the method from being flaky to be more consistend and predictable. This means that it **should be considered a breaking change** even if proposed as a bugfix.

Thanks for your attention and for your time.

### CODE REVIEW

**Comment by tilo** [comment]
@pioneerskies that makes sense - can you add some tests?

**Comment by pioneerskies** [comment]
> @pioneerskies that makes sense - can you add some tests?

Will do it. Thank you.

**Comment by pioneerskies** [comment]
I've updated fixtures and tests. This is the new list of tests in `spec/smarter_csv/column_separator_spec.rb`

```
can handle col_sep
  has default of comma as col_sep
  with explicitly given col_sep
    loads file with comma separator
    loads file with tab separator
    loads file with semi-colon separator
    loads file with colon separator
    loads file with pipe separator
  auto-detection of separator
    when file has headers
      auto-detects comma separator and loads data
      auto-detects tab separator and loads data
      auto-detects semi-colon separator and loads data
      auto-detects colon separator and loads data
      auto-detects pipe separator and loads data
      does not auto-detect other separators
      when auto is given as a string
        also works
    when file has not headers
      auto-detects comma separator and loads data
      auto-detects tab separator and loads data
      auto-detects semi-colon separator and loads data
      auto-detects colon separator and loads data
      auto-detects pipe separator and loads data
      does not auto-detect other separators
      when auto is given as a string
        also works
      when contents include a delimiter character with a count major than the number of colums
        will fail to guess the separator
```

I've duplicated the fixture to have a "no_headers" counterpart for each fixture with headers.

I've added a new column to fixtures with headers called `Trap` containing delimiter characters in values. These chars' count is greater than columns' count.

I've added the test

```
    when file has not headers
      when contents include a delimiter character with a count major than the number of columns
        will fail to guess the separator
```

which should demonstrate how the guessing algorithm could fail in some edge cases when headers are absent from the parsed CSV.

Ready to iterate in case you have any doubts/needs.

**Comment by tilo** [comment]
Thank you for your contribution, @pioneerskies ! 🙇

**Comment by tilo** [comment]
version 1.7.4 was just released with your contribution

**Pull request merged**
