### PR TITLE
Feature Request: Exposing invalid byte sequence errors in UTF-8

### PR DESCRIPTION
**Pull request by ghost**
Checking and replacing invalid byte sequence when :file_encoding => 'utf-8'.
Added option :invalid_byte_sequence to set replacing character.

### CODE REVIEW

**Comment by tilo** [comment]
right now the invalid bytes should be silently ignored - is that what you encountered?
Or did you see a crash?

**Comment by nathanpalmer** [comment]
Looks like I'm running into this same issue on a file that was received today.

`invalid byte sequence in UTF-8`

Here is the stack

```
/Users/nathan/.rvm/gems/ruby-2.2.3/gems/smarter_csv-1.1.0/lib/smarter_csv/smarter_csv.rb:94:in `=~': invalid byte sequence in UTF-8 (ArgumentError)
	from /Users/nathan/.rvm/gems/ruby-2.2.3/gems/smarter_csv-1.1.0/lib/smarter_csv/smarter_csv.rb:94:in `process'
	from /Users/nathan/Source/SocialDevLabs/Api/app/scenarios/format_conversion/pearl_paradise.rb:32:in `block in perform'
	from /Users/nathan/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/csv.rb:1273:in `open'
	from /Users/nathan/Source/SocialDevLabs/Api/app/scenarios/format_conversion/pearl_paradise.rb:9:in `perform'
	from /Users/nathan/.rvm/gems/ruby-2.2.3/bundler/gems/conderaction-be619243d62c/lib/dci/context.rb:12:in `perform'
	from /Users/nathan/.rvm/gems/ruby-2.2.3/gems/railties-4.2.3/lib/rails/commands/runner.rb:62:in `<top (required)>'
	from /Users/nathan/.rvm/gems/ruby-2.2.3/gems/railties-4.2.3/lib/rails/commands/runner.rb:62:in `eval'
	from /Users/nathan/.rvm/gems/ruby-2.2.3/gems/railties-4.2.3/lib/rails/commands/runner.rb:62:in `<top (required)>'
	from /Users/nathan/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/nathan/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/nathan/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/nathan/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/nathan/.rvm/gems/ruby-2.2.3/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /Users/nathan/.rvm/gems/ruby-2.2.3/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:90:in `runner'
	from /Users/nathan/.rvm/gems/ruby-2.2.3/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/nathan/.rvm/gems/ruby-2.2.3/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/nathan/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/nathan/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/nathan/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/nathan/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/nathan/Source/SocialDevLabs/Api/bin/rails:8:in `<top (required)>'
	from /Users/nathan/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
	from /Users/nathan/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/nathan/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/nathan/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
	from /Users/nathan/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/nathan/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

Adding the replace line certainly allows it to process without error.

**Comment by tilo** [comment]
thanks for the PR!

**Comment by tilo** [comment]
thank you for the PR - implemented in 1.1.1 with invalid_byte_sequence == ''

**Comment by kannannadarajan** [comment]
I am using smarter_csv 1.1.4 and facing the same issue.

/usr/local/rvm/gems/ruby-2.3.1/gems/smarter_csv-1.1.4/lib/smarter_csv/smarter_csv.rb:42:in `sub': invalid byte sequence in UTF-8 (ArgumentError)
        from /usr/local/rvm/gems/ruby-2.3.1/gems/smarter_csv-1.1.4/lib/smarter_csv/smarter_csv.rb:42:in `process'
        from import.rb:24:in `block in <main>'
        from import.rb:24:in `open'
        from import.rb:24:in `<main>'

I am using the line
File.open(file_name, "r:bom|utf-8") do |f| dataSet = SmarterCSV.process(f); end

May be useful for further fixes. 

Thanks for the wonderful gem.
Kannan

**Pull request closed without merging**
