### PR TITLE
Feature Request: Add ability of programmatically transforming headers

### PR DESCRIPTION
**Pull request by lbrigadin**

### CODE REVIEW

**Comment by agarie** [comment]
Why would you use such a transformation? What is your use case? It's interesting because I sometimes need to transform specific headers, but never all of them. :P

**Comment by lbrigadin** [comment]
We have csv files which have headers like FileType in camel case. And we need to transform them to underscore style (file_type). Thanks :)

**Comment by xufeiyun** [comment]
ha, this should be resolved by adding additional custom comments above the header line, thus the header just indicates the actual type

**Comment by tilo** [comment]
I think in 1.2.0 I will change the default behavior to not transform the headers at all, 
and then offer header conversions either through the already existing options, or through header transformations as suggested here.

```
#### 1.2.0 (2015-??-??)
 * changed default behavior of #parse method to not modify the existing headers in the CSV-file,
   unless explicitly requested. For backwards-compatibility please use these options:

To continue to use the old defaults, do this:

     old_defaults = {
       :downcase_header => true,
       :strip_whitespace => true,
       :remove_empty_values => true,
       :remove_zero_values => true,
       :convert_values_to_numeric => true,
       :remove_empty_hashes => true,
     }
    data = SmarterCSV.process("file.csv", old_defaults.merge(your_defaults) )
```

**Comment by tilo** [comment]
will be addressed in version 2.0

**Pull request closed without merging**
