### PR TITLE
Add :skip_lines option

### PR DESCRIPTION
**Pull request by wal**
Add a :skip_lines => N option that will skip the first N lines of a CSV file before starting to process. 

This is useful for CSV files that contain summary or other data before the main CSV data.

### CODE REVIEW

**Comment by netwire88** [comment]
Great idea!

**Comment by wal** [comment]
Hey @tilo  I'd love you to merge this please. What do you think ?

**Comment by davidahopp** [comment]
+1 on this merge. Will be using your fork @wal until it gets merged in!

**Comment by wal** [comment]
nudge @tilo

**Comment by tilo** [comment]
slated for 1.1.1  -- hopefully end of the week / weekend

**Comment by davidahopp** [comment]
@tilo, any word on 1.1.1 coming out?

**Comment by tilo** [comment]
+1 thanks for the PR!

**Comment by tilo** [comment]
added it manually to 1.1.1 -- thanks for the PR! 
sorry for the delay

**Pull request closed without merging**
