### PR TITLE
Switching to using an instance of the SmarterCSV::Reader class

### PR DESCRIPTION
**Pull request by tilo**
this PR fixes issues around SmarterCSV being thread-safe, e.g. in response to https://github.com/tilo/smarter_csv/pull/277

This PR moves away from using a module method, e.g. `SmarterCSV.process`, 
and instead using an instance `reader = SmarterCSV::Reader` that contains state, and calling `reader.process` on it.

For backwards compatibility there is a shim that allows existing code to use `SmarterCSV.process` for the simplest cases, but it no longer gives access to the internal state, e.g. headers, raw_headers, ...

Please update your code to the new calling mechanism.

### CODE REVIEW

**Review by jpcamara — COMMENTED** [review]
The overall approach looks great. Definitely like just making a distinct new Reader class and wrapping that. I've only been able to skim things so far, but seems like it would fix the threading issues!

**Comment by tilo** [comment]
> The overall approach looks great. Definitely like just making a distinct new Reader class and wrapping that. I've only been able to skim things so far, but seems like it would fix the threading issues!

I ran you test for a long time, and no issues.

**Comment by tilo** [comment]
@jpcamara @contentfree I'm releasing this as `1.12.0.pre1`

**Comment by chaadow** [comment]
hi @tilo thanks for merging this! Is it possible to update the Changelog to make it clear that this gem has become `thread safe` thanks!

**Comment by tilo** [comment]
> hi @tilo thanks for merging this! Is it possible to update the Changelog to make it clear that this gem has become `thread safe` thanks!

thanks for pointing that out! done!

**Pull request merged**
