### PR TITLE
Fix deprecation warnings for use of the $/ variable in 2.x branch

### PR DESCRIPTION
**Pull request by meagar**
This is a small fix to the 2.x branch to silence deprecation warnings related to use of `$/`.

Each call to `readline` or `chomp!` now passes in the row separator explicitly.

I don't have access to Ruby 2.x to run the gem's own test suite, but my own application's test suite passes (without deprecation warnings) and it does a lot of CSV parsing.

### CODE REVIEW

**Comment by tilo** [comment]
@meagar thank you for your contribution! 

I'd love to hear your feedback about the 2.x version

**Comment by meagar** [comment]
@tilo I don't really have any opinion, I haven't personally used the library directly. My company uses it extensively in a monolithic Ruby application, and it generates a *lot* of deprecation warnings when our test suite runs; the deprecation warnings are all I'm really concerned with fixing here.

**Comment by tilo** [comment]
@meagar my bad, the [PR for the main branch](https://github.com/tilo/smarter_csv/pull/187/files) has not yet been applied to the `2.0-develop` branch.

You should be using the `2.0-develop` branch..

**Comment by mscrivo** [comment]
> I'd love to hear your feedback about the 2.x version

hey @tilo I work with @meagar ... I was the one who moved us to 2.x back when it seemed 1.x was deprecated and wouldn't see further developed and we wanted to move to Ruby 3.0. It's been a while now, but I remember thinking to myself, wow this is a lot nicer and makes more sense when migrating the code from 1.x to 2.x patterns, if that helps at all. It's also been working well for us, no major issues at all. I do recall we had some problems with 1.x, but don't remember what they were now and they've probably since been solved.

**Pull request merged**
